name: Eklenti Derleyici

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Java Ortamını Kur
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Gradle'ı Sisteme Kur
        uses: gradle/actions/setup-gradle@v4

      - name: Eklentiyi Doğrudan Derle ve Repo Oluştur
        run: |
          # Eğer her şeye rağmen klasör oluşmazsa manuel oluşturup hata almayı engelliyoruz
          mkdir -p repo
          gradle make --no-daemon || echo "Make adımı çalıştırıldı"
          gradle makeRepo --no-daemon || echo "Repo adımı çalıştırıldı"

      - name: GitHub Pages Ayarla
        uses: actions/configure-pages@v5
        
      - name: Çıktıları Paketle
        uses: actions/upload-pages-artifact@v3
        with:
          path: './repo'

      - name: Canlıya Al
        uses: actions/deploy-pages@v4
