name: Eklenti Derleyici

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3

      - name: Java Ortamını Kur
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Derleme Yetkisi Ver
        run: chmod +x gradlew || true

      - name: Eklentiyi Derle ve Repo Oluştur
        run: |
          if [ -f ./gradlew ]; then
            ./gradlew make
            # Cloudstream için repo.json oluşturma komutu
            ./gradlew makeRepo
          else
            echo "Gradlew bulunamadı."
            exit 1
          fi

      - name: GitHub Pages'a Yükle
        uses: actions/configure-pages@v3
        
      - name: Çıktıları Paketle
        uses: actions/upload-pages-artifact@v1
        with:
          path: './repo'

      - name: Canlıya Al
        uses: actions/deploy-pages@v1
